#
Partie 1 – Series 
1) Créer une Series contenant 4 températures  
2) Afficher son index 
3) Afficher la 1ère valeur 
4) Afficher la dernière valeur 
5) Créer, de deux façon différentes, une Series de 4 températures avec comme index les heures de mesure 12h, 13h, 14h et 15h 
6) Afficher la 1ère et la dernière valeur

In [39]:
#Créer une Series contenant 4 températures
import pandas as pd
temperatures= pd.Series([24.5, 25.1, 26.3, 27.0])
temperatures

0    24.5
1    25.1
2    26.3
3    27.0
dtype: float64

In [40]:
#Afficher son index 
print(temperatures.index)

RangeIndex(start=0, stop=4, step=1)

In [41]:
#Afficher la 1ère valeur 
print("la 1ère valeur est :", temperatures.iloc[0])

la 1ère valeur est : 24.5

In [42]:
# Afficher la dernière valeur 
print("la dernière valeur est :", temperatures.iloc[-1])

la dernière valeur est : 27.0

In [43]:
#Créer, de deux façon différentes, une Series de 4 températures 
# avec comme index les heures de mesure 12h, 13h, 14h et 15h 
temperatures_heures= pd.Series([24.5, 25.1, 26.3, 27.0], index=['12h', '13h', '14h', '15h'])
print(temperatures_heures)

12h    24.5
13h    25.1
14h    26.3
15h    27.0
dtype: float64

In [44]:
temperature_dict = {'12h': 24.5, '13h': 25.1, '14h': 26.3, '15h': 27.0}
temperatures_heures_dict = pd.Series(temperature_dict)
print(temperatures_heures_dict)

12h    24.5
13h    25.1
14h    26.3
15h    27.0
dtype: float64

In [45]:
temperatures_heures2= pd.Series([24.5, 25.1, 26.3, 27.0])
temperatures_heures2.index = ['12h', '13h', '14h', '15h']
print(temperatures_heures2)

12h    24.5
13h    25.1
14h    26.3
15h    27.0
dtype: float64

In [46]:
#Afficher la 1ère et la dernière valeur 
print("la 1ère valeur est :", temperatures_heures.iloc[0])
print("la dernière valeur est :", temperatures_heures.iloc[-1])

la 1ère valeur est : 24.5
la dernière valeur est : 27.0

#
Partie 2 – DataFrame 
1) Créer et afficher le dataframe df_test à partir du dictionnaire suivant 

data = { "capteur": ["C001", "C002", "C003"], "temperature": [24.5, 25.1, 26.3], "humidite": [65, 67, 70] } 

2) Importer le dataset mesures_capteurs.csv dans le dataframe df 
3) Afficher les dimensions de df NB : dans la suite de l’atelier, on travaillera avec le dataframe df

In [47]:
#1) Créer et afficher le dataframe df_test à partir du dictionnaire suivant 
data = { "capteur": ["C001", "C002", "C003"], "temperature": [24.5, 25.1, 26.3], "humidite": [65, 67, 70] } 
df_test = pd.DataFrame(data)
df_test

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

In [52]:
#2) Importer le dataset mesures_capteurs.csv dans le dataframe df 
df=pd.read_csv("../data/mesures_capteurs.csv")
df

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
...,...,...,...,...,...,...,...,...,...
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

In [54]:
# Afficher les dimensions de df NB : dans la suite de l’atelier, on travaillera avec le dataframe df 
print("Dimensions (lignes, colonnes) :", df.shape)

Dimensions (lignes, colonnes) : (605, 9)